#! /usr/bin/env python2

import sys
import os
import re
import tweepy
import readline

class TweetShell:
	authfile = os.path.expanduser("~") + "/.twitter_auth"
	def __init__(self):
		a = map(lambda l: re.compile("^(.*?)(//.*)?$").search(l.strip()).group(0).rstrip().split(),
		        open(TweetShell.authfile))
		a = filter(lambda l: len(l) == 5, a)
		self.__auth = {}
		for t in a:
			self.__auth[t[0]] = tweepy.OAuthHandler(t[1], t[2])
			self.__auth[t[0]].set_access_token(t[3], t[4])

if __name__ == "__main__":
	if "-f" in sys.argv:
		idx = sys.argv.index("-f") + 1
		if idx == len(sys.argv, 1):
			sys.exit("-f option needs FILE NAME")
		TweetShell.authfile = sys.argv[idx]
	sh = TweetShell()
